---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: codegen-sep4-4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-sep4-4 
  name: codegen-sep4-4
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi